{% set name = "flexparser" %}
{% set version = "0.4" %}
{% set sha256 = "266d98905595be2ccc5da964fe0a2c3526fbbffdc45b65b3146d75db992ef6b2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<311]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - typing_extensions

test:
  imports:
    - {{ name }}
  requires:
    - pip
    - python
  commands:
    - pip check

about:
  home: https://github.com/hgrecco/flexparser
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Parsing made fun ... using typing.
  description: Parsing made fun ... using typing.
  dev_url: https://github.com/hgrecco/flexparser
  doc_url: https://github.com/hgrecco/flexparser?tab=readme-ov-file

extra:
  anaconda-services:
    ref:
      - https://anaconda.zendesk.com/agent/tickets/109074
  recipe-maintainers:
    - amaloney
